service: serverless-express-test

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1

package:
  exclude:
    - .git/**
    - test/**
    - README.md

functions:
  - ${file(./functions/function1/serverless.yml)}
  - ${file(./functions/function2/serverless.yml)}
